#!/bin/bash
# Program:
#
#   mbimcli-log-packet
#
#   Takes mbimcli verbose log from STDIN and filters out RAW packets and converts them into pcapng format
#
#     - Use sed for log filtering
#
#   Example:
#     $sudo mbimcli -v -d /dev/cdc-wdm0 --device-open-proxy --no-close --query-device-caps | ./mbimcli-log-packets > ./packet.pcapng
#
#   Or:
#     $sudo mbimcli -v -d /dev/cdc-wdm0 --device-open-proxy --no-close --query-device-caps > ./mbimcli.log
#     $./mbimcli-log-packets ./mbimcli.log ./packet.pcapng
#
#
#   The output pcapng file can be used for a 2nd review by Wireshark.
#
#
if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
    echo "Usage: "
    echo "    `basename $0` <infile> <outfile>"
    echo
    echo "where <infile>  specifies mbimcli debug log file (use - for standard input)"
    echo "      <outfile> specifies output packet file name, e.g., packet.pcapng"
    echo
    echo "Filter out MBIM RAW packets from ModemManger debug log and convert them into pcapng format."
    echo
    exit 0
fi

OUTPUT=$2

if [ ! "$OUTPUT" ] ; then
    OUTPUT=-
fi

sed -nzE 's/\n([<|>]+)/\t\1/gp' $1 | sed -nE -e 's/:/ /g' -e "s/\[([0-9]{2}) ([A-Za-z]{3}) ([0-9]{4}), ([0-9]{2}) ([0-9]{2}) ([0-9]{2})\].+(sent|received) message.+RAW .+data += ([0-9A-F ]+)/\[\1-\2 \3, \4:\5:\6\] 000000 \8/p" | text2pcap -n -t "[%d-%b %Y, %H:%M:%S]" -l 159 - $OUTPUT
